---
# tasks file for remove

# Debian
- block:

  - name: "Check if {{ package }} is removed"
    command: "dpkg-query -W {{ package }}"
    register: pack
    failed_when: pack.rc == 1
    changed_when: pack.rc > 1

  - block:
    #sudo app-get remove [package]
    - name: "APT remove {{ package }}"
      become: true
      ansible.builtin.apt:
        pkg:
          - "{{ package }}"
        state: absent
    when: pack.rc > 1
  
  when: ansible_os_family == 'Debian'