---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for purge

# APT remove with purge

# Debian
- block:

  - name: "Check if {{ package }} is removed"
    command: "dpkg-query -W {{ package}}"
    register: pack
    failed_when: pack.rc == 1
    changed_when: pack.rc > 1

  - block:
    #sudo app-get remove [package]
    - name: "APT remove {{ package }}"
      become: true
      ansible.builtin.apt:
        pkg:
          - "{{ package }}"
        state: absent
        purge: true
    when: pack.rc > 1
  
  when: ansible_os_family == 'Debian'