---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for dist_upgrade

# APT dist upgrade

# Debian
- block:
  - name : APT dist upgrade
    become: true
    apt:
      upgrade: dist
  when: ansible_os_family == 'Debian'