---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# APT update and keep in cache for a day + upgrade all to latest + autoremove
- hosts: all
  become: true
  collections:
    - fruafr.apt
  roles:
    - update
    - upgrade_latest_all
    - autoremove
