---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# APT - Upgrade all packages to latest
- hosts: all
  become: true
  collections:
    - fruafr.apt
  roles:
    - install_latest
  vars:
    package: '*'