---
# APT - Upgrade all packages to latest
# Author: David HEURTEVENT
# Date : 2023-09-17
- hosts: all
  become: true
  collections:
    - fruafr.apt
  roles:
    - install_latest
  vars:
    package: '*'