---
# tasks file for update

# Debian
- block:
  - name : APT update and keep in cache for a day
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day
  when: ansible_os_family == 'Debian'
