---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for autoremove

# APT autoremove

# Debian
- block:
  - name : APT autoremove
    become: true
    apt:
      autoremove: true
  when: ansible_os_family == 'Debian'